### ISSUE TITLE
使用rtmp推流时调用snap频繁时，会导致推流掉线

### ISSUE THREAD

**Issue by BySlin** [Monibuca/plugin-snap#1]
我使用obs推流时，2秒获取一个截图，m7s服务端接收10几个流，这十几个流会同时掉线，此时obs会触发重连

**Comment by langhuihui** [comment]
是否配置了delayclosetimeout

**Comment by BySlin** [comment]
没有配置，使用的默认配置，不使用截图功能时不会掉线，掉截图接口快了就会掉线

**Comment by BySlin** [comment]
新版本已修复
